# home:
   # path: /
   # controller: App\Controller\HomeController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# en lancer la route /logout l'utilisateur sera deconnecte
logout:
   path: /logout